/**
Each new term in the Fibonacci sequence
is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence
whose values do not exceed four million,
find the sum of the even-valued terms.
*/

// all fib # < 4MM
var prev = 1;
var curr = 1;
var term = 0;
var fsum = 0;

while (term < 4000000) {
  term = prev + curr;

  if (term % 2 === 0) {
    fsum += term;
  }

  prev = curr;
  curr = term;
}

// sum of even terms
console.log('for loop sum of even Fibonacci numbers under 4MM: ' + fsum);

phantom.exit();
